<?php

return [
'breadcrumb' => [
    'quotation' => 'Quotation',
    'quotations' => 'Quotations',
    'add_quotation' => 'Add Quotation',
    'edit_quotation' => 'Edit Quotation',
    'home' => 'Home',
],
'datatable' => [
    'add' => 'Add Quotation',
    'tools' => [
        'sEmptyTable' => 'No record found',
        'sInfo' => 'Show _START_ to _END_ from _TOTAL_ entry',
        'sInfoEmpty' => 'Show 0 to 0 from 0 data',
        'sInfoFiltered' => '(filtered from _MAX_ all entry)',
        'sInfoPostFix' => '',
        'sInfoThousands' => '.',
        'sLengthMenu' => 'Show _MENU_ entry',
        'sLoadingRecords' => 'Loading...',
        'sProcessing' => 'Processing...',
        'sSearch' => 'Cari:',
        'sZeroRecords' => 'No Record match',
        'oPaginate' => [
            'sFirst' => 'First',
            'sLast' => 'Last',
            'sNext' => 'Next',
            'sPrevious' => 'Previous'
        ],
        'oAria' => [
            'sSortAscending' => ': enable to sort columns Ascending',
            'sSortDescending' => ': enable to sort columns descending'
        ]
    ],
    'columns' => [
        'date' => 'Date',
        'reference' => 'Reference',
        'customer_name' => 'Customer Name',
        'amount' => 'Amount',
        'payment_method' => 'Payment Method',
        'action' => 'Action',
        'customer' => 'Customer',
        'status' => 'Status',
        'total_amount' => 'Total Amount',
        'paid_amount' => 'Paid Amount',
        'due_amount' => 'Due Amount',
        'payment_status' => 'Payment Status',
    ],
    'buttons' => [
        'excel' => 'Excel',
        'print' => 'Print',
        'reset' => 'Reset',
        'reload' => 'Reload'
    ]

],
'form' => [
    'reference' => 'Reference',
    'customer' => 'Customer',
    'date' => 'Date',
    'status' => 'Status',
    'send_invoice' => 'Send Invoice',
    'invoice_expiry_date' => 'Invoice Expiry Date',
    'note' => 'Note (If Needed)',
    'create_quotation' => 'Create Quotation',
    'status_options' => [
        'pending' => 'Pending',
        'sent' => 'Send to Email'
    ],
    'update_quotation' => 'Update Quotation',
    'edit' => 'Edit',
],
'page_title' => 'Edit Quotation',
'sale' => [
    'title' => 'Create Sale From Quotation',
    'make_sale' => 'Make Sale',
    'payment_method' => 'Payment Method',
    'amount_received' => 'Amount Received',
    'create_sale' => 'Create Sale',
    'status_options' => [
        'pending' => 'Pending',
        'shipped' => 'Shipped',
        'completed' => 'Completed'
    ],
    'payment_options' => [
        'cash' => 'Cash',
        'credit_card' => 'Credit Card',
        'bank_transfer' => 'Bank Transfer',
        'other' => 'Other'
    ]
],
'actions' => [
    'make_sale' => 'Make Sale',
    'send_email' => 'Send On Email',
    'edit' => 'Edit',
    'details' => 'Details',
    'delete' => 'Delete',
    'delete_confirm' => 'Are you sure? It will delete the data permanently!',
],
'email' => [
    'title' => 'Quotation',
    'thanks' => 'Thanks for Being Partner!',
    'our_quotation' => 'Our Quotation',
    'generated_by' => 'Generated by Kasir Mulia',
    'product' => 'Product',
    'price' => 'Price',
    'qty' => 'Qty',
    'discount' => 'Discount',
    'tax' => 'Tax',
    'sub_total' => 'Sub Total',
    'shipping' => 'Shipping',
    'total' => 'Total',
    'your_details' => 'Your Details',
    'customer_info' => 'Customer Information',
    'dear' => 'Dear',
    'interest_msg' => 'We hope you are interested in our products. If you want to order our products, For further information, please contact Our Phone Number',
    'or_email' => 'or Our Email',
    'additional_note' => 'Additional Note',
    'invoice_expire' => 'Invoice Expire Date',
    'thanks_customer' => 'Thanks for being great customer. Let it be!',
    'powered_by' => 'Powered by Kasir Mulia'
],
'print' => [
    'title' => 'Quotation Details',
    'reference' => 'Reference',
    'company_info' => 'Company Info',
    'customer_info' => 'Customer Info',
    'invoice_info' => 'Invoice Info',
    'invoice' => 'Invoice',
    'date' => 'Date',
    'status' => 'Status',
    'payment_status' => 'Payment Status',
    'email' => 'Email',
    'phone' => 'Phone',
    'table' => [
        'product' => 'Product',
        'net_unit_price' => 'Net Unit Price',
        'quantity' => 'Quantity',
        'discount' => 'Discount',
        'tax' => 'Tax',
        'sub_total' => 'Sub Total'
    ],
    'discount' => 'Discount',
    'tax' => 'Tax',
    'shipping' => 'Shipping',
    'grand_total' => 'Grand Total'
],
'show' => [
    'title' => 'Quotation Details',
    'details' => 'Details',
    'reference' => 'Reference',
    'print' => 'Print',
    'save' => 'Save',
    'company_info' => 'Company Info',
    'customer_info' => 'Customer Info',
    'invoice_info' => 'Invoice Info',
    'invoice' => 'Invoice',
    'date' => 'Date',
    'status' => 'Status',
    'payment_status' => 'Payment Status',
    'email' => 'Email',
    'phone' => 'Phone',
    'table' => [
        'product' => 'Product',
        'net_unit_price' => 'Net Unit Price',
        'quantity' => 'Quantity',
        'discount' => 'Discount',
        'tax' => 'Tax',
        'sub_total' => 'Sub Total'
    ],
    'discount' => 'Discount',
    'tax' => 'Tax',
    'shipping' => 'Shipping',
    'grand_total' => 'Grand Total'
],

];
